Add model
BIBSYSDEV/nva-file-model pull request #1
Opened 2021-11-01 08:58 UTC by brinxmat

- Adds fileset, file and license

2021-11-01 09:09 UTC, brinxmat commented on buildSrc/src/main/groovy/nvafilemodel.root.gradle
> +plugins{
If this file needs updating, please tell me

2021-11-01 09:09 UTC, brinxmat commented on gradle/libs.versions.toml
> +[versions]
This file is copied from datamodel-java and necessarily contains a lot of things that can be removed, however, before I do this, I think that it is interesting that nebula doesn't pick up on the fact that the definitions are unused. I guess that unused definitions are not included in gradle's dependency tree

2021-11-01 09:09 UTC, brinxmat commented on nva-file-model/build.gradle
> +    compileOnly libs.nva.commons.core
Here, on the other hand, I would have expected nebula-lint to complain

2021-11-01 09:09 UTC, brinxmat commented on nva-file-model/src/main/java/no/unit/nva/file/model/File.java
> +@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
This file requires a tidy, suggestions?

2021-11-01 09:09 UTC, brinxmat commented on nva-file-model/src/main/java/no/unit/nva/file/model/FileSet.java
> +    public FileSet(@JsonProperty(FILES) List<File> files) {
I changed this file, it had a builder…

2021-11-01 11:43 UTC, axthosarouris requested changes

2021-11-01 11:43 UTC, axthosarouris commented on buildSrc/src/main/groovy/nvafilemodel.publish-maven.gradle
> +                    url = 'https://github.com/BIBSYSDEV/nva-datamodel-java/tree/main'
update

2021-11-01 11:43 UTC, axthosarouris commented on buildSrc/src/main/groovy/nvafilemodel.publish-maven.gradle
> +                url = 'https://github.com/BIBSYSDEV/nva-datamodel-java'
update

2021-11-02 12:19 UTC, axthosarouris approved these changes

2021-11-02 14:39 UTC, merged